# Generated by Django 4.0.4 on 2022-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMigrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=15)),
                ('storeHash', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=50)),
                ('customer', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('description', models.CharField(max_length=500)),
                ('createdAt', models.TimeField(auto_now_add=True)),
                ('modifiedAt', models.TimeField(auto_now=True)),
            ],
        ),
    ]
