# Generated by Django 4.0.4 on 2022-04-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerMigrate',
        ),
    ]
